cafe-sync/src/fran/components/Layout.js
cafe-sync/src/fran/components/common.css
cafe-sync/src/fran/pages/main/Main.js
cafe-sync/src/fran/pages/main/Main.module.css

#8 
가맹점 메인 페이지 UI 구현하였습니다.
각 영역 내 텍스트 클릭 시 해당하는 페이지로 이동됩니다.
어떤 변경 사항이 있나요?
<br>

[25.02.10] 가맹점 메인 페이지 UI 구현

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/App.js
cafe-sync/src/apis/home/HomeApi.js
cafe-sync/src/apis/home/fetchWithAuth.js
cafe-sync/src/home/pages/login/Login.css
cafe-sync/src/home/pages/login/Login.js
cafe-sync/src/home/pages/protected-route/ProtectedRoute.js
cafe-sync/src/index.js
cafe-sync/src/redux/authSlice.js
cafe-sync/src/redux/store.js
cafe-sync/src/test/RegisterTest.js

#21 
로그인 API가 구현되었습니다
- apis/home 폴더 하위에 로그인 관련 API 정리해두었습니다
- 해당 API 호출 시 백엔드 서버에서 Access Token과 Refresh Token이 발급 됩니다
- Access Token 은 세션에 저장하도록 하였고 Refresh Token 은 Redis 서버에 저장하였습니다.
- Access Token 의 유효 시간은 15분으로 설정, Refresh Token 은 Redis 서버에 7일간 저장되도록 설정 해두어 보안을 강화해두었습니다
- 발급된 정보는 Redux Toolkit 을 이용하여 전역적으로 사용할 수 있도록 하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.11] 로그인 API 구현

---

cafe-sync/src/App.js

없음
앱.js 일부 코드 수정
어떤 변경 사항이 있나요?
<br>

[25.02.12] 코드 일부 수정

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/firebase/firebase.js
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/scripts/uploadImages.js

없음
메뉴 이미지 테스트로 인해 머지 하겠습니다
어떤 변경 사항이 있나요?
<br>

[25.02.13] 메뉴 이미지 테스트용

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/FullCalendar.module.css

#18 
스케줄 관리 페이지 조회 작업 마무리하였습니다.
UI적으로 더 작업하고 싶었으나, 시간이 지연되어 우선 다음 작업 시작할 예정입니다.
어떤 변경 사항이 있나요?
<br>

[25.02.14] 스케줄 관리 UI 구현 수정

---

cafe-sync/src/components/Modal.js
cafe-sync/src/components/Modal.module.css

#45 
공통 모달 UI 구현하였습니다.
어떤 변경 사항이 있나요?
<br>

[25.02.14] 공통 모달 UI 구현

---

cafe-sync/src/components/Modal.module.css
cafe-sync/src/components/ModalButton.module.css
cafe-sync/src/components/SModal.js

#45 
#56 
공통적으로 사용할 모달 UI 구현하였습니다.
사용 방법은 #56 을 참고하여 주시기 바랍니다.
어떤 변경 사항이 있나요?
<br>

[25.02.17] 공통 사용 모달 UI 구현

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js

- FullCalendar.js 오류 수정
- FullCalendar.js 오류 수정
어떤 변경 사항이 있나요?
<br>

[25.02.17] FullCalendar.js 오류 수정

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/inventory/Inventory.js

없음
충돌 수정되었습니다
어떤 변경 사항이 있나요?
<br>

[25.02.18] 충돌 수정

---

cafe-sync/src/App.js
cafe-sync/src/fran/pages/menus/itemList/CoffeeList.js
cafe-sync/src/fran/pages/menus/modal/MenuModal.js
cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
cafe-sync/src/fran/pages/menus/page/Menus.js
cafe-sync/src/fran/pages/menus/page/Menus.module.css
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/FranList.js
cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css

#69
- 메뉴검색완료
어떤 변경 사항이 있나요?
<br>

[25.02.19] 메뉴 검색 기능 구현

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/fran/pages/inventory/InOut.js
cafe-sync/src/fran/pages/inventory/InOut.module.css
cafe-sync/src/fran/pages/inventory/Inventory.js
cafe-sync/src/fran/pages/inventory/OutRegist.js
cafe-sync/src/fran/pages/inventory/OutRegist.module.css

#79 
- 로그인한 가맹점 기준으로 입출고 이력이 있다면 모두 조회해올 수 있도록 하였습니다
- 기간을 선택하여 조회할 수 있도록 하였습니다(전체조회 버튼을 클릭 시 모든 데이터를 다시 조회합니다)
- 한 페이지당 6개의 데이터를 조회할 수 있으며 그 이상으로 데이터 조회할 시 페이징으로 처리됩니다
- 목록으로 돌아가기를 선택할 시 초기 재고목록 화면으로 돌아갑니다
어떤 변경 사항이 있나요?
<br>

[25.02.19] 입출고 데이터 조회 및 페이징 처리

---

cafe-sync/src/apis/brista-note/baristaNoteApi.js
cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
cafe-sync/src/modules/NoteModule.js

86
파일첨부를 제외한 바리스타 노트 등록기능 그리고 제목에 등록취소했다가 다시 등록하면 데이터남는 버그 수정
어떤 변경 사항이 있나요?
<br>

[2025-02-19] 바리스타 노트 등록기능

---

cafe-sync/src/fran/pages/complain/Complain.js
cafe-sync/src/fran/pages/complain/components/ComplainAdd.js
cafe-sync/src/fran/pages/complain/components/ComplainList.js
cafe-sync/src/fran/pages/complain/styles/Complain.module.css
cafe-sync/src/fran/pages/employee/components/FullCalendar.js

#87 
컴플레인 페이지 UI 구현 중입니다.
전체적인 틀만 잡은 상태입니다.
어떤 변경 사항이 있나요?
<br>

[25.02.20] Feature/87(컴플레인페이지UI구현)

---

cafe-sync/src/apis/brista-note/baristaNoteApi.js
cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/fran/pages/inventory/InOut.js
cafe-sync/src/fran/pages/inventory/Inventory.js
cafe-sync/src/fran/pages/inventory/OutRegist.js

#93 
- 조회할 때 날짜 선택 시 마지막 날짜가 시작 날짜보다 빠를 수 없도록 처리하였습니다
- 출고 등록 시 본인 매장에서 보유하고 있는 수량 보다 많은 출고수량을 입력할 시 입력할 수 없도록 하였습니다
- 입출고 내역에서는 입고매장에서만 승인 및 취소할 수 있도록 하였습니다
- 이미 승인 또는 취소 처리가 되어있다면 처리할 수 없도록 하였습니다
- 승인 처리될 시 모달창을 닫으면 즉시 재고목록이 업데이트 되도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.20] 유효성 검사 및 입출고 승인, 취소 구현

---

cafe-sync/src/fran/pages/inventory/InOut.js
cafe-sync/src/fran/pages/inventory/InOutDetail.js
cafe-sync/src/fran/pages/inventory/InOutDetail.module.css

#97 
- 데이터는 기존 입출고 내역에서 props 로 받아와 내역을 보여줄 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.20] 입출고 상세내역 조회 UI 구현

---

cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/fran/pages/inventory/InOut.js
cafe-sync/src/fran/pages/inventory/InOutDetail.js
cafe-sync/src/fran/pages/inventory/InOutDetail.module.css
cafe-sync/src/fran/pages/inventory/Inventory.js

#99 
- 체크를 하지 않으면 발주 신청 할 수 없도록 하였습니다
- 발주 신청을 할 시 발주 신청이 되었습니다 라는 안내 문구가 출력됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.20] 발주신청 유효성검사 등록 안내 구현

---

cafe-sync/src/apis/brista-note/baristaNoteApi.js
cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
cafe-sync/src/fran/pages/barista-note/Note.module.css
cafe-sync/src/modules/NoteModule.js

110
바리스타 노트 삭제 기능
어떤 변경 사항이 있나요?
<br>

[25.02.21] 바리스타 노트 삭제 기능

---

cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/config/generateOrderPDF.js
cafe-sync/src/fran/pages/inventory/Orders.js
cafe-sync/src/fran/pages/inventory/Orders.module.css

#105 
- 로그인된 가맹점 기준으로 발주신청 했던 내역을 조회합니다
- 날짜를 선택하여 특정 날짜에 맞게 필터링이 가능합니다
- 끝나는 날짜가 시작날짜보다 빠르거나 시작날짜가 마지막 날자보다 이 후라면 경고 모달로 안내가 됩니다
- 제품 코드 및 제품명으로 발주내역 제품을 필터링 합니다
- 체크된 항목만 PDF 파일로 추출됩니다
- 체크하지 않을 시 경고 모달로 안내가 됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.21] 발주관리 UI, 유효성 검사, PDF 추출 기능 구현

---

cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/config/generateOrderPDF.js
cafe-sync/src/fran/pages/inventory/Orders.js
cafe-sync/src/fran/pages/inventory/Orders.module.css

#113  #114 
- 기존 발주 신청 내역에서 발주 상태가 아직 대기 상태이라면 발주 품목을 추가할 수 있습니다
- 만약 승인 및 반려 상태일 경우 추가, 저장, 삭제, 수량 변경 등 할 수 없도록 하였습니다
- 추가 버튼을 누른 후 모달창에서 필요한 제품을 선택 후 발주 수량을 입력할 수 있습니다
- 수량은 반드시 1개 이상 입력할 수 있도록 하였습니다(0 입력 불가)
- 추가할 항목이 이미 발주 목록에 있다면 추가할 수 없도록 하였습니다
- 추가된 항목을 체크한 뒤 반드시 저장 버튼을 눌러야 내역이 저장됩니다
- 저장 버튼은 체크를 하지 않으면 저장할 수 없도록 모달 안내 됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.21] 발주 내역 추가, 수정 구현

---

cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/fran/pages/inventory/InOut.js
cafe-sync/src/fran/pages/inventory/InOut.module.css
cafe-sync/src/fran/pages/inventory/Orders.js
cafe-sync/src/fran/pages/inventory/Orders.module.css

#115 #119 
- 체크된 항목만 삭제할 수 있도록 구현 되었습니다
- 체크하지 않을 시 삭제를 할 수 없도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.21] 발주 내역 삭제 기능 구현

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css

#43 
스케줄 조회 화면의 Month 를 주석 처리하였습니다. (필요하다면 추후 다시 추가할 예정입니다.)
스케줄 조회 시 스케줄 구분(시간 순서)별로 정렬되도록 설정하였습니다.
스케줄 등록 시 곧바로 화면에 적용되도록 조치하였습니다.
스케줄 등록할 때 '휴가'로 설정할 경우 날짜가 하루 전으로 돌아가는 문제 조치하였습니다. (KST가 아니라 발생한 이슈)
어떤 변경 사항이 있나요?
<br>

[25.02.21] 스케줄 조회 및 등록 로직 수정

---

cafe-sync/src/apis/slip/slipApi.js
cafe-sync/src/fran/pages/slip/Slip.js
cafe-sync/src/fran/pages/slip/Slip.module.css

#124 
- 날짜 범위에 있는 데이터를 조회할 수 있습니다
- 날짜를 선택하지 않거나 데이터가 없다면 안내창이 출력됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.22] 전표 조회

---

cafe-sync/src/fran/pages/slip/Slip.js

#125 #126 
- 전표 필드값 유효성 검사 추가
어떤 변경 사항이 있나요?
<br>

[25.02.23] 전표 필드값 유효성 검사 추가

---

cafe-sync/src/apis/slip/slipApi.js
cafe-sync/src/fran/pages/slip/Slip.js

#127 
- 체크된 항목만 삭제될 수 있도록 하였습니다
- 체크하지 않을 시 안내가 출력됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.23] 전표 삭제 구현

---

cafe-sync/src/apis/slip/slipApi.js
cafe-sync/src/fran/pages/slip/Slip.js
cafe-sync/src/fran/pages/slip/Slip.module.css

#128 #129 
- 구분 -> 차변(출금) 또는 대변(입금) 인 데이터만 세금 및 손익 계산서를 생성할 수 있습니다
- 체크된 항목한 생성할 수 있습니다
- 구분을 필터링 할 수 있도록 하였습니다
- 조회 로직은 현재는 더미데이터가 많이 없지만 만약 분기별 또는 1년 단위의
한 번에 많은 양의 데이터를 불러오게 되면 DB 과부하가 걸릴 수 있다고 생각하여 시작 날짜 기준 한달만 조회할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.23] 세금 및 손익 계산서 생성 구현

---

cafe-sync/src/apis/mgment/mgmentApi.js
cafe-sync/src/components/ModalButton.module.css
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js

- 136
- 가맹점 상세페이지
어떤 변경 사항이 있나요?
<br>

[25.02.24] 가맹점 상세페이지

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/apis/slip/slipApi.js
cafe-sync/src/config/generateInvoicePDF.js
cafe-sync/src/fran/pages/inventory/Orders.module.css
cafe-sync/src/fran/pages/slip/Duty.js
cafe-sync/src/fran/pages/slip/Duty.module.css
cafe-sync/src/fran/pages/slip/Slip.js
cafe-sync/src/fran/pages/slip/Slip.module.css
cafe-sync/src/home/pages/login/Login.css

#138 
- 로그인한 가맹점의 정보로 전체 조회합니다
- 데이터가 많다면 페이징 처리할 수 있도록 하였습니다
- 검색 필터링에서 시작날짜가 마지막 날짜보다 이 후라면 검색할 수 없도록 하였습니다
- 만약 데이터가 없다면 없다고 안내 문구가 출력됩니다
- 세금 계산서 상세 내용에서 PDF 파일로 추출 할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.02.24] 세금 계산서 조회 기능 구현

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css

#135 
신규 등록되는 데이터끼리 중복 검사
기존 등록되어 있는 데이터와의 중복 검사
어떤 변경 사항이 있나요?
<br>

[25.02.24] 스케줄 등록 중복(유효성) 검사

---

cafe-sync/src/apis/mgment/mgmentApi.js
cafe-sync/src/apis/slip/slipApi.js
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css
cafe-sync/src/fran/pages/slip/Duty.js
cafe-sync/src/fran/pages/slip/Slip.js
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/FranDelete.js
cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
cafe-sync/src/hq/pages/mgment/itemList/FranModify.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css

#150 
- 세금 계산서 삭제 기능이 구현되었습니다
- 체크된 항목만 삭제할 수 있도록 하였습니다
- 세금 계산서 삭제할 시 세금 계산서만 삭제되고 전표 삭제 시 관련된 세금 계산서까지 모두 삭제됩니다
어떤 변경 사항이 있나요?
<br>

[25.02.25] 세금 계산서 삭제

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/apis/mgment/mgmentApi.js
cafe-sync/src/apis/notice/noticeApi.js
cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css
cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
cafe-sync/src/fran/pages/notice/NoticeLayout.js
cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/FranDelete.js
cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
cafe-sync/src/hq/pages/mgment/itemList/FranModify.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css
cafe-sync/src/modules/NoticeModule.js

124
공지사항 새로고침시 조회수추가되는 것 막음
전체페이지에서 상세페이지에 들어갈때만 조회수 증가
어떤 변경 사항이 있나요?
<br>

[25.02.25] 공지사항 새로고침시 조회수추가되는 것 막음

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/apis/mgment/mgmentApi.js
cafe-sync/src/apis/notice/noticeApi.js
cafe-sync/src/fran/pages/barista-note/NoteRegist.module.css
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/styles/ScheduleAdd.module.css
cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
cafe-sync/src/fran/pages/notice/NoticeLayout.js
cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/FranDelete.js
cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
cafe-sync/src/hq/pages/mgment/itemList/FranModify.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css
cafe-sync/src/modules/NoticeModule.js

157
공지사항 검색 기능
어떤 변경 사항이 있나요?
<br>

[25.02.25] 공지사항 검색 기능

---

cafe-sync/src/fran/pages/menus/page/Menus.js

없음
- 메뉴 버그 수정
어떤 변경 사항이 있나요?
<br>

[25.02.25] 메뉴 버그 수정

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleModify.js

#153 
스케줄 관리 내 스케줄 수정 버튼 추가 및 동작 로직 설정
어떤 변경 사항이 있나요?
<br>

[25.02.25] 스케줄 관리 수정

---

cafe-sync/src/App.js
cafe-sync/src/apis/menus/menusApi.js
cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
cafe-sync/src/hq/pages/menus/HQCoffeeList.js
cafe-sync/src/hq/pages/menus/HQMenuModal.js
cafe-sync/src/hq/pages/menus/HQMenus.js
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js

- 181
- 본사 메뉴 전체 조회
어떤 변경 사항이 있나요?
<br>

[25.02.27] 본사 메뉴 전체 조회

---

cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/components/ScheduleModify.js

#177  #178
스케줄 삭제 로직 추가
스케줄 등록/수정/삭제 시 정상 반영되도록 버그 수정 및 개선
어떤 변경 사항이 있나요?
<br>

[25.02.27] 스케줄 삭제 및 조회 버그 수정

---

cafe-sync/src/fran/components/common.css
cafe-sync/src/fran/pages/complain/Complain.js
cafe-sync/src/fran/pages/complain/components/ComplainAdd.js
cafe-sync/src/fran/pages/complain/components/ComplainList.js
cafe-sync/src/fran/pages/complain/styles/Complain.module.css
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js
cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
cafe-sync/src/fran/pages/employee/hooks/useFetchWorkers.js

#187 
로그인한 계정의 가맹점 근로자 목록을 생각보다 자주 불러오고 있어, 불러오는 커스텀 훅 생성
어떤 변경 사항이 있나요?
<br>

[25.02.27] 로그인한 계정의 가맹점 근로자 목록 불러오는 커스텀 훅 생성

---

cafe-sync/src/fran/pages/menus/modal/MenuModal.module.css
cafe-sync/src/hq/pages/menus/HQCoffeeList.js
cafe-sync/src/hq/pages/menus/HQMenuModal.js
cafe-sync/src/hq/pages/menus/HQMenuModal.module.css
cafe-sync/src/hq/pages/menus/HQMenus.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js

- 191
- 본사 메뉴 수정
어떤 변경 사항이 있나요?
<br>

[25.02.28] 본사 메뉴 수정

---

cafe-sync/src/hq/pages/menus/HQMenuModal.js

- 200
- 본사 메뉴 등록
어떤 변경 사항이 있나요?
<br>

[25.02.28] 본사 메뉴 등록

---

cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
cafe-sync/src/fran/pages/notice/NoticeDetailLayout.js
cafe-sync/src/fran/pages/notice/NoticeRegistLayout.js

[25.02.28] 공지사항 SModal 적용

---

cafe-sync/package-lock.json
cafe-sync/public/index.html
cafe-sync/src/apis/inventory/vendorApi.js
cafe-sync/src/firebase/firebase.js
cafe-sync/src/firebase/uploadImageToFirebase.js
cafe-sync/src/fran/pages/barista-note/Note.module.css
cafe-sync/src/hq/pages/inventory/HQVendor.js
cafe-sync/src/hq/pages/inventory/HQVendor.module.css

#208 
- 본사 페이지 공급업체 관리 기능이 구현되었습니다
- 신규 업체 등록을 할 수 있습니다
- 이미지 등록 시 구글 클라우드와 Firebase를 연동하여 클라우드 서버에 저장되도록 하였습니다
- 정확한 주소지 입력을 위해 다음 API 주소를 활용하였습니다
- 값을 하나라도 입력하지 않을 시 버튼이 비활성화 됩니다
어떤 변경 사항이 있나요?
<br>

[25.03.04] 공급업체 관리

---

cafe-sync/src/App.js
cafe-sync/src/firebase/uploadMenuImageToFirebase.js
cafe-sync/src/fran/pages/menus/itemList/MenuList.module.css
cafe-sync/src/fran/pages/menus/page/Menus.js
cafe-sync/src/fran/pages/menus/page/Menus.module.css
cafe-sync/src/hq/components/Sidebar.js
cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
cafe-sync/src/hq/pages/menus/HQDiscontinue.js
cafe-sync/src/hq/pages/menus/HQDiscontinueList.js
cafe-sync/src/hq/pages/menus/HQLayout.js
cafe-sync/src/hq/pages/menus/HQMenuModal.js
cafe-sync/src/hq/pages/menus/HQMenuModal.module.css
cafe-sync/src/hq/pages/menus/HQMenus.js

#213 
- 본사 메뉴 관리 수정 및 단종 메뉴 기능 추가되었습니다
- 수정 시 메뉴 사진도 수정할 수 있게끔 변경했습니다 (이미지는 Firebase에 저장되도록 하였습니다)
- 단종 버튼 클릭 시 자동으로 단종 메뉴 페이지로 이동 됩니다 단종 메뉴는 솔드아웃으로 표현됩니다
어떤 변경 사항이 있나요?
<br>

[25.03.05] 본사 메뉴 관리(수정, 단종 기능 추가)

---

cafe-sync/src/apis/mgment/mgmentApi.js
cafe-sync/src/firebase/uploadFranImageToFirebase.js
cafe-sync/src/fran/pages/menus/page/CategoryButtons.js
cafe-sync/src/fran/pages/menus/page/Menus.js
cafe-sync/src/hq/pages/menus/HQCategoryButtons.js
cafe-sync/src/hq/pages/menus/HQMenus.js
cafe-sync/src/hq/pages/mgment/HQMgment.js
cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.js
cafe-sync/src/hq/pages/mgment/itemList/EmpSearchModal.module.css
cafe-sync/src/hq/pages/mgment/itemList/FranList.module.css
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.js
cafe-sync/src/hq/pages/mgment/itemList/FranRegist.module.css

#217 
- 본사 가맹점 관리 수정 및 등록 로직 수정, UI 변경되었습니다
- 수정 및 등록에서 필드값이 하나라도 없다면 등록 및 수정할 수 없도록 하였습니다
- 등록할 때 가맹점 코드는 DB에서 확인 후 없는 가맹점 코드로 부여하는 방향으로 변경 되었습니다
- 사번 코드로 등록하는 것이 아닌 이름으로 등록할 수 있게 UI를 변경하였습니다
- 가맹점 이미지는 Firebase 에 저장할 수 있도록 하였습니다 
- 주소 찾기는 다음 API 를 활용하였습니다
어떤 변경 사항이 있나요?
<br>

[25.03.05] 본사 가맹점 관리 수정 및 등록 로직 수정, UI 변경

---

cafe-sync/src/apis/employee/employeeApi.js
cafe-sync/src/firebase/uploadProfileImageToFirebase.js
cafe-sync/src/fran/components/Sidebar.js
cafe-sync/src/fran/pages/employee/Employee.js
cafe-sync/src/fran/pages/employee/Employee.module.css
cafe-sync/src/fran/pages/employee/EmployeeDetail.js
cafe-sync/src/fran/pages/employee/EmployeeDetail.module.css

#230 
- 가맹점 직원관리 기능이 구현되었습니다
- 점장 직급일 경우에만 수정 및 신규 직원 등록이 가능합니다
- 바리스타 직급일 경우 버튼이 안보이도록 하였습니다
- 수정이나 등록할 경우 메모 및 퇴사일을 제외한 나머지 필드값을 입력하지 않았으면 등록할 수 없도록 하였습니다
- 주소 변경이나 입력 시 다음 API 사용 하였습니다
- 프로필 이미지는 Firebase에 저장할 수 있도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.03.06] 가맹점 직원관리

---

cafe-sync/src/fran/pages/complain/components/ComplainAdd.js
cafe-sync/src/fran/pages/complain/components/ComplainList.js

[25.03.06] basic -> main

---

cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
cafe-sync/src/fran/pages/complain/components/ComplainList.js
cafe-sync/src/fran/pages/employee/components/ScheduleAdd.js

#228 
컴플레인 상세 조회 구현
어떤 변경 사항이 있나요?
<br>

[25.03.05] 컴플레인 상세 조회 구현

---

cafe-sync/src/fran/pages/complain/components/ComplainList.js
cafe-sync/src/fran/pages/complain/styles/Complain.module.css

#235 
컴플레인 페이징 처리
어떤 변경 사항이 있나요?
<br>

[25.03.06] 컴플레인 페이징 처리

---

cafe-sync/src/fran/pages/complain/components/ComplainList.js
cafe-sync/src/fran/pages/complain/styles/Complain.module.css
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
cafe-sync/src/fran/pages/main/Main.js
cafe-sync/src/fran/pages/main/Main.module.css
cafe-sync/src/fran/pages/main/components/ScheduleCalendar.js

#240 
가맹점 메인화면 - 스케줄 구현
어떤 변경 사항이 있나요?
<br>

[25.03.06] 가맹점 메인화면 - 스케줄 구현

---

cafe-sync/src/apis/notice/noticeApi.js
cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
cafe-sync/src/fran/pages/main/Main.js
cafe-sync/src/fran/pages/main/Main.module.css
cafe-sync/src/fran/pages/main/components/DailySalesChart.js
cafe-sync/src/fran/pages/main/components/InventoryShortageList.js
cafe-sync/src/fran/pages/main/components/InventoryShortageList.module.css
cafe-sync/src/fran/pages/main/components/NoticeList.js
cafe-sync/src/fran/pages/main/components/NoticeList.module.css
cafe-sync/src/fran/pages/main/components/SalesBarGraph.js
cafe-sync/src/fran/pages/stats/MenuStats.module.css
cafe-sync/src/hq/pages/notice/HQNoticeRegistLayout.js

#245 
- 가맹점 메인화면 UI 구현 되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.07] 메인화면 데이터 표현하기

---

cafe-sync/src/fran/pages/stats/MenuStats.js
cafe-sync/src/fran/pages/stats/MenuStats.module.css
cafe-sync/src/hq/pages/stats/HQStats.js
cafe-sync/src/hq/pages/stats/MonthlySalesChart.js
cafe-sync/src/hq/pages/stats/StatChart.js
cafe-sync/src/hq/pages/stats/StoreSales.js
cafe-sync/src/hq/pages/stats/menuSalseChart.js
cafe-sync/src/hq/pages/stats/stat.css
cafe-sync/src/hq/pages/stats/todaySalesChart.js

- 249
- 본사 통계
어떤 변경 사항이 있나요?
<br>

[25.03.07] 본사 통계

---

cafe-sync/src/hq/pages/inventory/HQFranInventory.js
cafe-sync/src/hq/pages/inventory/HQFranInventory.module.css
cafe-sync/src/hq/pages/inventory/HQInventoryTableHeader.js
cafe-sync/src/hq/pages/inventory/HQInventoryTableHeader.module.css

#254 
- 본사 가맹점 관리 추가 되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.07] 본사 가맹점 관리 추가

---

cafe-sync/src/fran/pages/main/Main.js
cafe-sync/src/hq/pages/plan/HQPlan.js
cafe-sync/src/hq/pages/plan/PlanCalendar.js
cafe-sync/src/hq/pages/plan/styles/Plan.module.css

#248 
일정 관리 UI 구현
어떤 변경 사항이 있나요?
<br>

[25.03.07] 일정 관리 UI 구현

---

cafe-sync/src/fran/pages/slip/Duty.js
cafe-sync/src/hq/pages/slip/HQDuty.js
cafe-sync/src/hq/pages/slip/HQDuty.module.css

#260 
- 본사 세금, 손익 계산서 추가 되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.08] 본사 세금, 손익 계산서 추가

---

cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
cafe-sync/src/hq/pages/plan/PlanCalendar.js
cafe-sync/src/hq/pages/plan/styles/Plan.module.css

#255 
일정 관리 조회 로직
어떤 변경 사항이 있나요?
<br>

[25.03.07] 일정 관리 조회 로직

---

cafe-sync/src/hq/pages/slip/HQIncome.js
cafe-sync/src/hq/pages/slip/HQIncome.module.css

- 본사 손익 계산서 추가
어떤 변경 사항이 있나요?
<br>

[25.03.08] 본사 손익 계산서 추가

---

cafe-sync/src/hq/pages/chat/HQChat.js
cafe-sync/src/hq/pages/chat/HQChat.module.css
cafe-sync/src/hq/pages/chat/HQChatting.js
cafe-sync/src/hq/pages/chat/HQChatting.module.css
cafe-sync/src/hq/pages/chat/HQCreateChatRoom.js
cafe-sync/src/hq/pages/chat/HQCreateChatRoom.module.css
cafe-sync/src/hq/pages/chat/HQEmployee.js
cafe-sync/src/hq/pages/chat/HQEmployee.module.css
cafe-sync/src/hq/pages/chat/HQRoom.js
cafe-sync/src/hq/pages/chat/HQRoom.module.css

#266 
- 본사 채팅 기능이 추가 되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.08] 본사 채팅 기능 추가

---

cafe-sync/src/apis/inventory/inventoryApi.js
cafe-sync/src/fran/pages/inventory/Inventory.js
cafe-sync/src/fran/pages/inventory/Orders.js
cafe-sync/src/hq/pages/inventory/HQOrders.js
cafe-sync/src/hq/pages/inventory/HQOrders.module.css

#268 
- 본사 발주내역 승인 반려 기능이 추가되었습니다
어떤 변경 사항이 있나요?
<br>

[25.03.08] 본사 발주내역 승인 반려 추가

---

cafe-sync/src/fran/pages/inventory/Orders.js
cafe-sync/src/hq/pages/inventory/HQOrders.js

[25.03.08] 페이징수 조정

---

cafe-sync/src/apis/home/HomeApi.js
cafe-sync/src/apis/home/fetchWithAuth.js
cafe-sync/src/fran/components/Header.js
cafe-sync/src/fran/components/common.css
cafe-sync/src/fran/pages/employee/EmployeeDetail.js
cafe-sync/src/hq/components/Header.js
cafe-sync/src/redux/authSlice.js
cafe-sync/src/redux/store.js

#271 
- 본사 가맹점 헤더 부분에 토큰 연장 및 만료 시 자동 로그아웃 기능을 추가하였습니다
- AccessToken 은 15분 동안만 유효합니다
- Redis 에 저장된 RefreshToken 을 기반으로 AccessToken을 발급합니다
- 단순히 프론트에서 타이머를 재는 것이 아닌 서버에서 토큰을 발급할 때 토큰 발행시간을 함께 프론트로 넘기므로
- 실제 토큰 유지시간을 동기화 되도록 하였습니다
어떤 변경 사항이 있나요?
<br>

[25.03.08] 토큰 연장 및 만료 시 자동 로그아웃 기능 추가

---

cafe-sync/src/App.js
cafe-sync/src/home/components/NotFoundPage.js
cafe-sync/src/home/components/NotFoundPage.module.css

#273 
- 라우트 설정 외 다른 URL 접근 시 별도로 구현한 404 에러 페이지로 이동할 수 있도록 추가하였습니다 
어떤 변경 사항이 있나요?
<br>

[25.03.08] 404 에러 페이지 추가

---

cafe-sync/src/hq/pages/stats/HQStats.js

없음
컴포넌트 경로 수정
어떤 변경 사항이 있나요?
<br>

[25.03.12] 컴포넌트 경로 수정

---

cafe-sync/src/hq/pages/stats/HQStats.js
cafe-sync/src/hq/pages/stats/TodaySalesChart2.js
cafe-sync/src/hq/pages/stats/stat.module.css

[25.03.12] 컴포넌트 수정

---

cafe-sync/package.json

[25.03.12] json 수정

---

cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
cafe-sync/src/hq/pages/plan/AddPlan.js
cafe-sync/src/hq/pages/plan/DetailPlan.js
cafe-sync/src/hq/pages/plan/ModifyPlan.js
cafe-sync/src/hq/pages/plan/PlanCalendar.js
cafe-sync/src/hq/pages/plan/styles/Plan.module.css

#284 
일정 관리 CSS 조정
어떤 변경 사항이 있나요?
<br>

[25.03.12] 일정 CSS 조정

---

cafe-sync/src/fran/pages/complain/components/ComplainDetail.js
cafe-sync/src/fran/pages/employee/components/FullCalendar.js
cafe-sync/src/fran/pages/employee/components/ScheduleModify.js
cafe-sync/src/hq/pages/plan/AddPlan.js
cafe-sync/src/hq/pages/plan/DetailPlan.js
cafe-sync/src/hq/pages/plan/ModifyPlan.js
cafe-sync/src/hq/pages/plan/PlanCalendar.js
cafe-sync/src/hq/pages/plan/styles/Plan.module.css

#262 #277 #278 #282 
일정 등록 로직 작성
일정 상세 조회 로직 작성
일정 수정 로직 작성
일정 삭제 로직 작성
어떤 변경 사항이 있나요?
<br>

[25.03.12] 일정 등록, 수정, 삭제

---

cafe-sync/src/hq/pages/stats/StoreSales.js
cafe-sync/src/hq/pages/stats/stat.module.css

- 275
- 본사통계 CSS
어떤 변경 사항이 있나요?
<br>

[25.03.12] 본사통계 CSS

---

cafe-sync/src/fran/pages/barista-note/BaristaNoteLayout.js
cafe-sync/src/fran/pages/inventory/FranInventory.module.css
cafe-sync/src/fran/pages/slip/Duty.module.css
cafe-sync/src/hq/pages/barista-note/BaristaNoteLayout.js
cafe-sync/src/hq/pages/inventory/HQFranInventory.module.css

- 세금계산서 css 수정 되었습니다.
어떤 변경 사항이 있나요?
<br>

[25.03.12] 세금계산서  css 수정

---

cafe-sync/package-lock.json
cafe-sync/package.json
cafe-sync/src/fran/pages/employee/styles/FullCalendar.module.css
cafe-sync/src/hq/pages/main/HQMain.js
cafe-sync/src/hq/pages/main/components/HQPromotion.js
cafe-sync/src/hq/pages/main/components/HQPromotion.module.css
cafe-sync/src/hq/pages/plan/styles/Plan.module.css
cafe-sync/src/hq/pages/stats/stat.module.css

#289 
일정 관리 CSS 조정
어떤 변경 사항이 있나요?
<br>

[25.03.13] 일정 관리 CSS 조정

---

cafe-sync/package.json

[25.03.13] 배포 테스트 6번째

---

cafe-sync/package.json

[25.03.13] 배포 테스트 7번째

---

cafe-sync/package.json

[25.03.13] 배포 테스트 8번째

---

cafe-sync/craco.config.js
cafe-sync/package-lock.json
cafe-sync/package.json

[25.03.13] 배포 테스트 9번째

---

cafe-sync/craco.config.js
cafe-sync/package.json

[25.03.13] 배포 테스트 10번째

---

cafe-sync/craco.config.js
cafe-sync/package-lock.json
cafe-sync/package.json

[25.03.13] 배포 테스트 11번째

---

cafe-sync/package.json

[25.03.13] 배포 테스트 12번째

---

cafe-sync/package.json

[25.03.13] 배포 테스트 13번째

---

cafe-sync/package-lock.json
cafe-sync/package.json

[25.03.13] 배포 테스트 14번째

---

cafe-sync/src/hq/pages/plan/AddPlan.js
cafe-sync/src/hq/pages/plan/ModifyPlan.js

[25.03.14] 일정 관리 코드 수정
